CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"username" text NOT NULL,
	"password" text NOT NULL,
	CONSTRAINT "users_username_unique" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "website_configs" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"template_type" text DEFAULT 'professionals' NOT NULL,
	"logo" text,
	"hero_image" text,
	"profile_image" text,
	"default_language" text DEFAULT 'es' NOT NULL,
	"show_why_website_button" boolean DEFAULT true,
	"show_domain_button" boolean DEFAULT true,
	"show_chatbot" boolean DEFAULT true,
	"whatsapp_number" text,
	"whatsapp_message" json,
	"facebook_url" text,
	"instagram_url" text,
	"social_link" text,
	"google_maps_embed" text,
	"address" json,
	"phone" text,
	"email" text,
	"office_hours" json,
	"analytics_code" text,
	"primary_color" text DEFAULT '#C8102E',
	"secondary_color" text DEFAULT '#00A859',
	"background_color" text DEFAULT '#FFFFFF',
	"ai_optimized_note" text DEFAULT 'AI-optimized for speed and search',
	"banner_text" json,
	"banner_background_color" text DEFAULT '#FFC107',
	"banner_text_color" text DEFAULT '#000000',
	"banner_text_size" text DEFAULT '16px',
	"show_banner" boolean DEFAULT false,
	"pricing_banner_bg_color" text DEFAULT '#17A2B8',
	"pricing_banner_text_color" text DEFAULT '#FFFFFF',
	"payment_banner_bg_color" text DEFAULT '#FFFFFF',
	"payment_banner_text_color" text DEFAULT '#333333',
	"hero_image_opacity" text DEFAULT '0.5',
	"hero_image_position" text DEFAULT 'center',
	"hero_section_height" text DEFAULT '70vh',
	"hero_text_alignment" text DEFAULT 'text-center',
	"hero_text_color" text DEFAULT '#ffffff',
	"hero_subtext_color" text DEFAULT '#ffffff',
	"hero_title_size" text DEFAULT '3.5rem',
	"hero_subtitle_size" text DEFAULT '1.25rem',
	"hero_vertical_alignment" text DEFAULT 'center',
	"pro_hero_image" text,
	"pro_hero_image_opacity" text DEFAULT '0.8',
	"translations" json,
	"doctor_name" text,
	"business_name" text,
	"specialty" json,
	"hero_title" json,
	"hero_subtitle" json,
	"hero_description" json,
	"about_title" json,
	"about_text" json,
	"about_stats" json,
	"services_title" json,
	"services" json,
	"menu_images" json DEFAULT '[]'::json,
	"menu_pages" json DEFAULT '[]'::json,
	"tours" json,
	"products" json,
	"service_areas" json,
	"reviews" json,
	"photos" json,
	"chatbot_questions" json DEFAULT '[]'::json,
	"chatbot_icon" text DEFAULT '📞',
	"chatbot_color" text DEFAULT '#007BFF',
	"chatbot_title" json,
	"chatbot_welcome" json,
	"why_points" json DEFAULT '[]'::json,
	"service_steps_title" json,
	"service_steps_description" json,
	"service_steps" json DEFAULT '[]'::json,
	"template_showcase_images" json DEFAULT '[]'::json,
	"templates" json DEFAULT '[]'::json,
	"solutions_title" json,
	"solutions_overview" json DEFAULT '[]'::json,
	"pro_banner_text" json,
	"pro_banner_background_color" text DEFAULT '#C8102E',
	"pro_banner_text_color" text DEFAULT '#FFFFFF',
	"show_pro_banner" boolean DEFAULT true,
	"pro_whatsapp_buttons" json DEFAULT '[]'::json,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
